name: Dispatch to Repo
on: 
  push:
    tags:
      - "v*"
  workflow_dispatch:
    
jobs:
  dispatch:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: ["pit-ninja/repository.pit-ninja"]
    steps:
      - name: Push to repo
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: update
          client-payload: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}", "module": "pit-ninja/screensaver.atv4", "tag": "${{ github.ref_name }}"}'